- name: Apache
  action: apt pkg=apache2 state=installed

- name: Apache required modules
  action: command a2enmod {{ item }}
  notify: restart apache
  with_items:
    - rewrite
    - vhost_alias
    - headers
    - expires
    - filter
    - ssl

- name: Push default virtual host configuration
  copy: src={{ project_name }} dest=/etc/apache2/sites-available/ mode=0640

- name: Deactivates the default virtualhost
  command: a2dissite default

- name: Deactivates the default ssl virtualhost
  command: a2dissite default-ssl

- name: Activates our virtualhost
  command: a2ensite {{ project_name }}
  notify:
    - restart apache

- name: PHP core and required modules
  action: apt pkg={{ item }} state=installed
  notify: restart apache
  tags: common
  with_items:
    - php5
    - php5-mysql
    - php5-xmlrpc
    - php-soap
    - php5-gd
    - php-apc
    - php5-curl
    - php5-intl
    - php5-memcache
    - php5-memcached

# Only install the client, you may want to use the DB-server on a different machine
- name: MySQL Client only
  action: apt pkg=mysql-client state=installed

# Need this to run mysql commands via Ansible
- name: Ensure python-mysqldb is available
  apt: pkg=python-mysqldb state=installed

- name: cURL
  action: apt pkg=curl state=installed