- name: Install Apache
  apt: pkg=apache2 state=installed

- name: Push configuration files
  template:
    src={{ item }}.j2
    dest=/etc/apache2/{{ item }}
    owner=root group=root mode=0644
  with_items:
  - envvars

- name: Deactivates the default virtualhost
  command: a2dissite default

- name: Deactivates the default ssl virtualhost
  command: a2dissite default-ssl

- name: Remove default index file from default docroot
  file: path=/var/www/index.html state=absent

- name: Push project virtualhosts
  template:
    src="virtualhost.j2"
    dest="/etc/apache2/sites-available/{{ item.name }}"
  with_items: projects
  notify:
    - apache-restart

- name: Activates project virtualhosts
  command: a2ensite {{ item.name }}
  with_items: projects
  notify:
    - apache-restart

# - name: Push virtualhost configuration template
#   template:
#     src=default_virtualhost.j2
#     dest="/etc/apache2/sites-available/{{ project_name }}"
#   notify:
#   - apache-restart

# - name: Activates our virtualhost
#   command: a2ensite {{ project_name }}
#   notify:
#     - apache-restart

# Activate modules
- name: Enable modules
  command: a2enmod {{ item }} creates="/etc/apache2/mods-enabled/{{ item }}.load"
  with_items: apache_modules
  when: apache_modules is defined
  notify:
  - apache-restart

# Ensure service is running.
- name: Ensure deamon is running correctly
  service: name=apache2 state=started