- name: "Install the distribution's Ruby base packages"
  apt: pkg={{ item }} state=installed
  with_items:
  - ruby

- name: Install Ruby gem usual dependencies
  apt: pkg={{ item }} state=installed
  with_items:
  - libssl-dev
  - zlib1g-dev
  - ruby-bundler
  - rubygems
  - libxml2   # nokogiri needs this, and most applications use nokogiri

# Put this in an extra file, and load a gem's dependencies before the gem itself.
- name: Install gems
  gem: name={{ item }} state=latest
  with_items: ruby_gems

#Install sass and compass in specific locations
- name: Sass
  action: command gem install sass creates=/usr/local/bin/sass

- name: Compass
  action: command gem install compass creates=/usr/local/bin/compass
  #gem: name=compass version=1.0.0.alpha.19 state=present