# The default settings are optimized for a development installation.
# You'll probably want to rethink this on a production server.
php_memory_limit: '256M'
php_max_execution_time: '60'
php_max_input_time: '60'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_error_reporting: 'E_ALL | E_STRICT'
php_post_max_size: '64M'
php_upload_max_filesize: '64M'
php_main_timezone: '{{ timezone }}'