# - name: Update perch config for projects
#   template:
#     src=config.php.j2
#     dest="{{ item.document_root }}/perch/config/config.php"
#   with_items: projects
#   when: item.cms == "perchcms"

- name: Update wordpress config for projects
  template:
    src=wp-config-sample.php.j2
    dest="{{ item.document_root }}/wp-config.php"
    owner=www-data group=www-data mode=0775
  with_items: projects
  when: item.cms == "wordpress"

# - name: set config file permissions correctly
#   file: path={{ site_root}}/public/wp-config.php owner=www-data group=www-data mode=0775

# - name: set web root folder permissions
#   file: path={{ site_root }}/public state=directory owner=www-data group=www-data mode=0755