- name: Install misc utils
  apt: pkg={{ item }} state=present
  with_items:
  - python-mysqldb # Need this to run mysql commands via Ansible

- name: Client
  action: apt pkg=mysql-client state=installed

- name: Server
  action: apt pkg=mysql-server state=installed
  notify: restart mysql

- name: Ensure project database exists
  mysql_db: name={{ item.name }} state=present
  with_items: projects
  when: item.mysql

- name: Create DB users
  mysql_user: name={{ item.name }} password={{ item.db_user.password }} priv={{ item.db_user.priv }} host='%' state=present
  with_items: projects
  when: item.mysql