- name: Check for previous installation of Node
  shell: "[ -f /usr/local/bin/node ]"
  ignore_errors: True
  register: node_exists

- include: main_ubuntu.yml
  when: ansible_distribution == "Ubuntu" and node_exists|failed

- name: Install npm package {{ item }}
  npm:
    global=yes
    name={{ item }}
    state=present
  with_items:
    - grunt-cli
    - bower

#Only run npm install if package.json exists
- name: Check if package.json exists
  command: /usr/bin/test -e {{ site_root }}/package.json
  register: node_package
  ignore_errors: yes

- name: Install local npm packages from package.json
  action: npm path={{ site_root }}
  when: node_package|success