- name: Add Chris-Lea nodejs repository
  apt_repository: repo="ppa:chris-lea/node.js"

- name: Install Node + NPM packages
  apt: pkg=nodejs state=present update_cache=yes

- name: Install npm package {{ item }}
  npm:
    global=yes
    name={{ item }}
    state=present
  with_items:
    - grunt-cli
    - bower

#Only run npm install if package.json exists
# - name: Check if package.json exists in projects
#   command: /usr/bin/test -e {{ item.site_root }}/package.json
#   register: node_package
#   ignore_errors: yes
#   with_items: projects

#Only run npm install if package.json exists
# - name: Check if package.json exists
#   command: /usr/bin/test -e {{ site_root }}/package.json
  # register: node_package
  # ignore_errors: yes

# - name: Install local npm packages from package.json
#   action: npm path={{ site_root }}
#   when: node_package|success