---
# This playbook will set up a vagrant box for generic LAMP development.
# See the various roles (especially roles/*/tasks/main.yml) for more details.

# Looks for the [vagrant] section in the hosts file to determine which machines
# to operate on.

- hosts: vagrant
  sudo: yes

  vars:
    timezone: 'Pacific/Auckland'
    # projects:
    #   - { name: "project_name",
    #       site_root: "/var/www/project_folder",
    #       document_root: "/var/www/project_root",
    #       mysql: true,
    #       db_user: "{{ db_users.project_name }}",
    #       cms: perchcms,
    #       licenses: "{{ licenses.project_name }}" }
    #   - { name: "project_name",
    #       site_root: "/var/www/project_folder",
    #       document_root: "/var/www/project_root",
    #       mysql: true,
    #       db_user: "{{ db_users.project_name }}",
    #       cms: wordpress }

  roles:
    - common
    - apache
    - php
    - mysql
    - vagrant
    - git
    - node
    - ruby

    # Configs for cms's
    - perchcms
    - wordpress