---
# This playbook will set up a vagrant box for generic LAMP development.
# See the various roles (especially roles/*/tasks/main.yml) for more details.

# Looks for the [vagrant] section in the hosts file to determine which machines
# to operate on.

# Each role has it's own defaults, look in role/default for role configuration

- hosts: vagrant
  sudo: yes

  vars:
    timezone: 'Pacific/Auckland'
    db_server: 127.0.0.1

  vars_files:
    - settings/databases.yml
    - settings/licenses.yml
    - settings/projects.yml

  roles:
    - common
    - apache
    - php
    - mysql
    - vagrant
    - git
    - node
    - ruby

    # Configs for cms's
    - perchcms
    - wordpress