---
# This playbook will set up a vagrant box for generic LAMP development.
# See the various roles (especially roles/*/tasks/main.yml) for more details.

# Looks for the [vagrant] section in the hosts file to determine which machines
# to operate on.
- hosts: vagrant
  sudo: True

  # Looks for roles/{role}/tasks/main.yml for tasks, roles/{role}/handlers/main.yml
  # for handlers, etcetera.
  roles:
    - common
    - apache
    - server-init
    - fail2ban
    - ufw
    - mysql
    - php
    - git

    # CMS specific
    # - perchcms
    #- wordpress